### ISSUE TITLE
Get clarification / refinements to the Expert Reviewed / All Data toggle on the beta site

### ISSUE THREAD

**Issue by benedictpaten** [BD2KGenomics/brca-website#103]
Agreeing with @maryjgoldman, the current menu bar is a mess. I particularly dislike the confusing "DEFAULT MODE/RESEARCH PAGES" toggle, which conflates state (the fact the button label changes) with being a menu. 

I propose the following:

- (Credit to Mary) Adding a MORE menu button on the far right. Clicking on this button would reveal less common features.

- Move "RESEARCH/DEFAULT PAGES" to the MORE button, renaming it "DETAIL MODE"

- Move "ABOUT" to more

Later, we can add "VERSION" to this "MORE" menu. (also credit to Mary).

What do others think?

**Comment by melissacline** [comment]
Opening an LShift Trello card: https://trello.com/c/IdE0GJpS/27-add-more-menu-button-to-the-menu-bar

**Comment by melissacline** [comment]
Now that we're down to tweaks on the toggle, it's time to restart with a new issue.
