### ISSUE TITLE
Change in the text above the research portal

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-website#108]
I was looking at the website and noticed text above the research portal that I hadn't read before:

This is the BRCA Exchange Research Space. It contains information drawn from multiple databases and intelligently merged together, one row per allele. It is intended to provide researchers as comprehensive as possible set of BRCA variations and annotations.

Could we edit to the following for readability and syntax? 

This is the BRCA Exchange Research Space. It contains information drawn from multiple databases which have been intelligently merged together, one row per variant. It is intended to provide researchers with a set of BRCA variations and annotations which is as comprehensive as possible.

**Comment by maryjgoldman** [comment]
@strbean  Can we add this to the Tier 1 cleanup and add it to beta?

**Comment by strbean** [comment]
This is already live on beta, plus some changes for the "expert reviewed" => "all public data" terminology change.
