### ISSUE TITLE
Change the delimiter in the download file from a comma to a tab

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-website#111]

**Comment by melissacline** [comment]
Molly, you fixed this, correct?  Is the change checked into github?

**Comment by MollyZhang** [comment]
I did not fix this. I had trouble finding where that line is. Could it be assigned to new web developer?

**Comment by melissacline** [comment]
This question pertains to the Download link on the Variants page in All Public Data portal.  Moving forward, when we have new data on the website, we'd like the download file to be tab-delimited rather than comma-delimited.  Is the download file generated on the fly from the database, or is there a pre-existing file that gets downloaded?  If the latter, then updating the file will resolve this issue.

**Comment by zfisch** [comment]
@melissacline what's our status on this? Is this still something that needs to be done?

**Comment by melissacline** [comment]
When the user clicks on the Download button on the Variants page, what is it that's actually downloaded?  I strongly suspect (but I'm not positive) that it's the file that's loaded into the database.  It could be a live database dump, but it seems too quick for that...

If it's the file that we're loading into the database, then it _will_ be tab-delimited in the next release.

And given that we've got comma-delimited fields, providing a comma-delimited download file would be silly.

**Comment by zfisch** [comment]
Got it, checking rn.
