### ISSUE TITLE
Remove scroll to zoom on lolliplot?

### ISSUE THREAD

**Issue by maryjgoldman** [BD2KGenomics/brca-website#130]
Scrolling to zoom can be frustrating when you are trying to scroll down the page, especially since you can double click to zoom in anyways.

**Comment by strbean** [comment]
Funny, I was running into this issue when investigating the performance issues! Frustrating indeed.

**Comment by strbean** [comment]
Looks like this is going to harder than it should be. The D3 drawing library, which the lolliplot uses, didn't add the option of ignoring certain event types until a much later version.

**Comment by melissacline** [comment]
@maryjgoldman if this is going to be hard to fix, how important do you think it is?

**Comment by cmarkello** [comment]
@strbean, are you looking at the lollipop github repo? It might be easier to have more powerful control over the tool if you can edit the source?
This particular version of lollipop can be found [here](https://github.com/cmarkello/muts-needle-plot).

**Comment by maryjgoldman** [comment]
I don't think it's that important to fix. It's annoying but users can work around this. Also, it's not an often used feature at this point. We can revisit if we get feedback from users.

**Comment by cmarkello** [comment]
Yeah when I was developing this, I ran into this issue months ago, but couldn't find the right tools to solve it. Basically my temporary work-around was to embed the interactive plot within a button that's default-closed and relying on user discretion in using the tool. It performs universally well after filtering the data when there are few elements rendered. Basically it's dependent on the clients hardware as far as rendering and performance is concerned which is not ideal and should be binned based on zoom level.
