### ISSUE TITLE
Table column disappears when paging

### ISSUE THREAD

**Issue by david4096** [BD2KGenomics/brca-website#161]
On mac safari I observed that the table display changes when paging. I don't believe this is intended as I can't see the allele frequency.

![brca_table_bug](https://cloud.githubusercontent.com/assets/3795586/17266495/ef21dfb0-55ad-11e6-8da2-79e6a3803a45.gif)

**Comment by strbean** [comment]
Looks like the table is just overflowing to the right and getting cut off. Some indication that this is what is happening would clear things up.

**Comment by david4096** [comment]
@strbean Yes, it appears to be a problem with the table columns changing size when paging.

**Comment by zfisch** [comment]
strange, I'm looking into it now.

**Comment by zfisch** [comment]
ah yea, this is related to issue #145 -- I'll put in a PR to standardize table column sizes based on screen size and make sure there's a scrollbar on the table if the width of the screen is too small to contain the entire table.
