### ISSUE TITLE
Link the "?" in the header of the variant table to the appropriate text (see details)

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-website#40]
One more trivial thing: when you are looking at a variant record, there is a little "?" you can click on to get more information on what a field like "gene symbol" means, and what the formal spec for it is. When you click on that you go to a help page, but at least for my browser you don't go to the right place in that help page. It would be good if either

(a) this click got you to a separate page that is entirely devoted to the one concept/field, e.g. a single page for just "gene symbol", or

(b) you were careful to get to the right place in the combined page, and you highlight the concept/field, so the user sees that they got to where they wanted to go to.

**Comment by acthp** [comment]
dup of #99
