### ISSUE TITLE
Add functionality to handle HGVS strings with the reference sequence specified (see details)

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-website#41]
1. home page. search for "NM_007294.3(BRCA1):c.-20+11C>T". In the
javascript console I get the exception:

Error: Invariant Violation: Missing "c" parameter for path
"/variants?search=NM_007294.3(BRCA1):c.-20+11C>T"

(note: specifying the reference sequence is what seems to throw off the search)

**Comment by acthp** [comment]
The javascript error is a separate issue from correctly handling the reference id. I believe the javascript error has been resolved, but the feature request remains. So, not a bug.
