### ISSUE TITLE
Can't copy text from variants table (see details)

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-website#42]
Results table. Hard to copy and paste text from table because it
seems to count as a click. As if the onmousedown event is being used
in stead of onclick.

**Comment by acthp** [comment]
This may be hard to fix. We're using the onclick handler. We can implement our own using onmousedown and onmouseup, which may consume some time, or devise a different UI that doesn't handle clicks on the text. Or we can ignore this for now.

**Comment by melissacline** [comment]
In that case, let's ignore it for now.

**Comment by acthp** [comment]
I thought of a workaround for this, so have committed it.
