### ISSUE TITLE
help text fix

### ISSUE THREAD

**Issue by benedictpaten** [BD2KGenomics/brca-website#97]
On the help page:

The text below doesn't explain the defaults that are assumed if you don't include a specific reference sequence. The examples assume that. Most people assume that. 

Searching

To search just start typing a variant in the search box and it will auto complete. Variants are identified using HGVS nomenclature, a standard created by the Human Genome Variation Society. Most genetic test results are reported in HGVS nomenclature. This nomenclature describes a variant by indicating (1) a reference sequence, (2) what kind of sequence it is (genomic, cDNA or protein), (3) the position of the variant in relation this reference sequence, and (4) the nucloetide or protein differences between the variant and the reference sequence. For example, NM_007294.3:c.5053A>G indicates a variant relative to reference sequence NM_007294.3, which is a cDNA sequence (as indicated by c), that the variant is in position 5053, and that it involves changing an A to a G.

----------

In this line:

Benign variants are not associated with any markedly increased risk of disease.

you need to use the agreed upon term "benign /little clinical significance"

**Comment by melissacline** [comment]
Added an LShift Trello card: https://trello.com/c/IdE0GJpS/27-add-more-menu-button-to-the-menu-bar
